rules:
    # Possible errors
    annotation-no-unknown: true
    color-no-invalid-hex: true
    font-family-no-duplicate-names: true
    font-family-no-missing-generic-family-keyword: true
    named-grid-areas-no-invalid: true
    function-calc-no-unspaced-operator: true
    function-linear-gradient-no-nonstandard-direction: true
    function-no-unknown: true
    string-no-newline: true
    unit-no-unknown: true
    custom-property-no-missing-var-function: true
    property-no-unknown: true
    keyframe-declaration-no-important: true
    keyframe-block-no-duplicate-selectors: true
    declaration-block-no-duplicate-custom-properties: true
    declaration-block-no-duplicate-properties: true
    declaration-block-no-shorthand-property-overrides: true
    block-no-empty: true
    selector-pseudo-class-no-unknown: true
    selector-pseudo-element-no-unknown: true
    selector-type-no-unknown: true
    media-feature-name-no-unknown: true
    at-rule-no-unknown: true
    comment-no-empty: true
    no-descending-specificity: true
    no-duplicate-at-import-rules: true
    no-duplicate-selectors: true
    no-empty-source: true
    no-invalid-double-slash-comments: true
    no-invalid-position-at-import-rule: true

    # Limit language features
    alpha-value-notation: "number"
    hue-degree-notation: "angle"
    color-function-notation: "modern"
    # color-hex-alpha: "never"
    color-hex-length: "short"
    # color-named: "never"
    # color-no-hex: true
    length-zero-no-unit: true
    font-family-name-quotes: "always-where-recommended"
    font-weight-notation: "named-where-possible"
    # function-allowed-list: ""
    # function-disallowed-list: ""
    function-url-no-scheme-relative: true
    function-url-quotes: ["always", except: ["empty"]]
    # function-url-scheme-allowed-list: ""
    # function-url-scheme-disallowed-list: ""
    import-notation: "url"
    keyframe-selector-notation: "percentage-unless-within-keyword-only-block"
    # keyframes-name-pattern: ""
    # number-max-precision: 0
    # time-min-milliseconds: 0
    # unit-allowed-list: ""
    # unit-disallowed-list: ""
    shorthand-property-no-redundant-values: true
    value-no-vendor-prefix: true
    custom-property-pattern: "^[a-z][\\da-z]*(?:-[\\da-z]+)*$"
    # property-allowed-list: ""
    # property-disallowed-list: ""
    property-no-vendor-prefix: true
    # declaration-no-important: ""
    # declaration-property-unit-allowed-list: ""
    # declaration-property-unit-disallowed-list: ""
    # declaration-property-value-allowed-list: ""
    # declaration-property-value-disallowed-list: ""
    declaration-block-no-redundant-longhand-properties: true
    # declaration-block-single-line-max-declarations: 0
    # selector-attribute-name-disallowed-list: ""
    # selector-attribute-operator-allowed-list: ""
    # selector-attribute-operator-disallowed-list: ""
    selector-attribute-quotes: "always"
    selector-class-pattern: "^[a-z][\\da-z]*(?:-[\\da-z]+)*$"
    # selector-combinator-allowed-list: ""
    # selector-combinator-disallowed-list: ""
    # selector-disallowed-list: ""
    selector-id-pattern: "^[a-z][\\da-z]*(?:-[\\da-z]+)*$"
    selector-max-attribute: 3
    selector-max-class: 5
    selector-max-combinators: 3
    selector-max-compound-selectors: 5
    selector-max-id: 2
    selector-max-pseudo-class: 3
    # selector-max-specificity: ""
    selector-max-type: 5
    selector-max-universal: 1
    # selector-nested-pattern: ""
    # selector-no-qualifying-type: ""
    selector-no-vendor-prefix: true
    selector-not-notation: "complex"
    # selector-pseudo-class-allowed-list: ""
    # selector-pseudo-class-disallowed-list: ""
    # selector-pseudo-element-allowed-list: ""
    selector-pseudo-element-colon-notation: "double"
    # selector-pseudo-element-disallowed-list: ""
    # rule-selector-property-disallowed-list: ""
    # media-feature-name-allowed-list: ""
    # media-feature-name-disallowed-list: ""
    media-feature-name-no-vendor-prefix: true
    # media-feature-name-value-allowed-list: ""
    # custom-media-pattern: ""
    # at-rule-allowed-list: ""
    # at-rule-disallowed-list: ""
    at-rule-no-vendor-prefix: true
    # at-rule-property-required-list: ""
    # comment-pattern: ""
    # comment-word-disallowed-list: ""
    # max-nesting-depth: 0
    no-irregular-whitespace: true
    no-unknown-animations: true
    unicode-bom: "never"

    # Stylistic issues
    value-keyword-case: "lower"
    function-name-case: "lower"
    # custom-property-empty-line-before: ""
    selector-type-case: "lower"
    rule-empty-line-before: "always-multi-line"
    at-rule-empty-line-before: "always"
    # comment-empty-line-before: ""
    comment-whitespace-inside: "always"
    color-hex-case: "lower"
    # function-comma-newline-after: ""
    # function-comma-newline-before: ""
    function-comma-space-after: "always"
    function-comma-space-before: "never"
    function-max-empty-lines: 0
    # function-parentheses-newline-inside: "always"
    function-parentheses-space-inside: "never"
    function-whitespace-after: "always"
    number-leading-zero: "always"
    number-no-trailing-zeros: true
    string-quotes: "double"
    unit-case: "lower"
    # value-list-comma-newline-after: ""
    # value-list-comma-newline-before: ""
    value-list-comma-space-after: "always"
    value-list-comma-space-before: "never"
    value-list-max-empty-lines: 0
    property-case: "lower"
    declaration-bang-space-after: "never"
    declaration-bang-space-before: "always"
    # declaration-colon-newline-after: ""
    declaration-colon-space-after: "always"
    declaration-colon-space-before: "never"
    declaration-empty-line-before: "never"
    declaration-block-semicolon-newline-after: "always-multi-line"
    declaration-block-semicolon-newline-before: "never-multi-line"
    declaration-block-semicolon-space-after: "always-single-line"
    declaration-block-semicolon-space-before: "never"
    declaration-block-trailing-semicolon: "always"
    block-closing-brace-empty-line-before: "never"
    block-closing-brace-newline-after: "always"
    # block-closing-brace-newline-before: ""
    # block-closing-brace-space-after: ""
    # block-closing-brace-space-before: ""
    # block-opening-brace-newline-after: ""
    # block-opening-brace-newline-before: ""
    block-opening-brace-space-after: "always-single-line"
    block-opening-brace-space-before: "always-multi-line"
    selector-attribute-brackets-space-inside: "never"
    selector-attribute-operator-space-after: "never"
    selector-attribute-operator-space-before: "never"
    selector-combinator-space-after: "always"
    selector-combinator-space-before: "always"
    selector-descendant-combinator-no-non-space: true
    selector-max-empty-lines: 2
    selector-pseudo-class-case: "lower"
    selector-pseudo-class-parentheses-space-inside: "never"
    selector-pseudo-element-case: "lower"
    # selector-list-comma-newline-after: "always-multi-line"
    selector-list-comma-newline-before: "never-multi-line"
    selector-list-comma-space-after: "always-single-line"
    selector-list-comma-space-before: "never"
    media-feature-colon-space-after: "always"
    media-feature-colon-space-before: "never"
    media-feature-name-case: "lower"
    media-feature-parentheses-space-inside: "never"
    media-feature-range-operator-space-after: "always"
    media-feature-range-operator-space-before: "always"
    # media-query-list-comma-newline-after: ""
    # media-query-list-comma-newline-before: ""
    media-query-list-comma-space-after: "always-single-line"
    media-query-list-comma-space-before: "never"
    at-rule-name-case: "lower"
    # at-rule-name-newline-after: ""
    at-rule-name-space-after: "always"
    at-rule-semicolon-newline-after: "always"
    at-rule-semicolon-space-before: "never"
    indentation: "tab"
    linebreaks: "unix"
    max-empty-lines: 2
    max-line-length: 80
    no-eol-whitespace: true
    no-missing-end-of-source-newline: true
    no-empty-first-line: true
    no-extra-semicolons: true
